# 100 numpy exercises (Optional)

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [86]:
import numpy as np 

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [ ]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np 

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.26.0'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
Z = np.zeros(10)
print(Z) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [6]:
Z=np.zeros((10,10))
print("%d bytes" %(Z.size*Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
z=np.zeros(10)
z[4]=1
print(z) 

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
z=np.arange(10,50)
print(z) 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
z=np.arange(10,50)
print(z) 
x=z[::-1]
print(x) 

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
z=np.arange(9).reshape(3,3)
print(z) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [13]:
z=np.nonzero([1,2,0,0,4,0])
print(z) 

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
z=np.eye(3)
print(z) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [18]:
z=np.random.random((3,3,3))
print(z)  

[[[0.35884859 0.04302035 0.40640594]
  [0.15065722 0.44461632 0.94025474]
  [0.39609364 0.13233752 0.51719799]]

 [[0.66685319 0.47197496 0.54499967]
  [0.27454338 0.35717648 0.2269599 ]
  [0.59576017 0.1031214  0.60859624]]

 [[0.23292529 0.10047641 0.55182689]
  [0.99451807 0.19464118 0.29924634]
  [0.46756239 0.38977731 0.34104294]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [21]:
z=np.random.random((10,10))
z 
z_max,z_min = z.max(),z.min()
print(z_max,z_min)  

0.9929850126136464 0.013359710247177303


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [22]:
z=np.random.random(30)
m=z.mean()
print(m) 

0.4434101679926624


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
z=np.ones((10,10))
z[1:-1,1:-1]=0 
print(z) 

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [26]:
z=np.ones((5,5)) 
z=np.pad(z,pad_width=1,mode='constant',constant_values=0)
print(z) 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan                o/p : nan
np.nan == np.nan          o/p : False , nan values are not equal in numpy 
np.inf > np.nan           o/p : False , Infinity is not greater than NaN)
np.nan - np.nan           o/p : nan 
np.nan in set([np.nan])   o/p : True
0.3 == 3 * 0.1            o/p : False,Due to floating-point 3*0.1,its not exactly equal
```

In [36]:
x= 3*0.1 
x 

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [38]:
a=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
a 

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [42]:
print("Main diagonal : ",np.diag(a))
print("Upper of Main diagonal : ",np.diag(a+1))
print("Lower Main diagonal : ",np.diag(a-1))

Main diagonal :  [1 5 9]
Upper of Main diagonal :  [ 2  6 10]
Lower Main diagonal :  [0 4 8]


Now Question Answer 

In [48]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z) 

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [58]:
z=np.zeros((8,8))
z[1::2,::2]=1 
z[::2,1::2]=1 
z 

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [63]:
print(np.unravel_index(99,(6,7,8))) 

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [67]:
z=np.tile(np.array([[0,1],[1,0]]),(4,4)) 
print(z) 

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
z=np.random.mat

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [69]:
color=np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)]) 
color 

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [74]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z) 

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [76]:
z=np.arange(11) 
z[(3<z) & (z<8)] *=-1
z 

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [78]:
from numpy import * 
print(sum(range(5),-1)) 

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [80]:
np.array(0) / np.array(0) 

C:\Users\shouv\AppData\Local\Temp\ipykernel_21892\3120514017.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [81]:
np.array(0) // np.array(0)  

C:\Users\shouv\AppData\Local\Temp\ipykernel_21892\591090683.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [82]:
np.array([np.nan]).astype(int).astype(float) 

C:\Users\shouv\AppData\Local\Temp\ipykernel_21892\3939184219.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [84]:
z=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(z)),z)) 

[-10.   5.  10.  -1.  -3.   7.  -8.  -6.   6.  -2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [91]:
x=np.random.randint(0,10,10)
y=np.random.randint(0,10,10) 
z=np.intersect1d(x,y) 
print(z)  

[4 5 7 8 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [92]:
defaults=np.seterr(all="ignore") 
z=np.ones(1)/0 
print(z) 

[inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [93]:
np.sqrt(-1) == np.emath.sqrt(-1) 

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [98]:
today =np.datetime64('today') 
yesterday =np.datetime64('today') - np.timedelta64(1) 
tomorrow  =np.datetime64('today') + np.timedelta64(1) 

In [99]:
today 

numpy.datetime64('2023-10-19')

In [100]:
yesterday 

numpy.datetime64('2023-10-18')

In [101]:
tomorrow 

numpy.datetime64('2023-10-20')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [103]:
z=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(z)  

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [105]:
A=np.ones(3)*1 
B=np.ones(3)*2 
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)  

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [112]:
z=np.random.uniform(0,10,10)
# print(z-z%1)  
# print(z//1)  
print(np.floor(z))  
# print(z.astype(int)) 

[7. 2. 8. 8. 5. 5. 9. 8. 8. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [116]:
z=np.zeros((5,5))
z+=np.arange(5)
z=np.tile(np.arange(0,5),(5,1)) 
z 

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 
#### integers and use it to build an array (★☆☆)

In [117]:
def generate():
    for x in range(10):
        yield x 
z=np.fromiter(generate(),dtype=float,count=-1)
print(z) 

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [121]:
z=np.linspace(0,1,11,endpoint=False)[1:]   
z 

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [124]:
z=np.random.random(10)
z.sort()
z  

array([0.03565242, 0.1253447 , 0.1430982 , 0.2022462 , 0.27061899,
       0.31756588, 0.40398086, 0.50749683, 0.53053861, 0.62333181])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [126]:
z=np.arange(10) 
np.add.reduce(z) 

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [128]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
check=np.allclose(A,B) 
print(check)  

False


#### 43. Make an array immutable (read-only) (★★☆)

In [131]:
z=np.zeros(10) 
z.flags.writeable=False
z[0]=1 

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [133]:
z=np.random.random((10,2))
x,y = z[:,0],z[:,1] 
r=np.sqrt(x**2+y**2) 
t=np.arctan2(y,x) 
print(r) 
print(t) 

[0.86221591 0.36527608 0.83979958 0.3832287  0.9228097  0.30843047
 1.00383907 0.4015175  0.8307972  0.83239944]
[0.46219832 0.14676702 1.52546118 0.10026214 0.21009298 0.38437387
 0.59316794 0.12299333 1.34663106 1.3833279 ]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [135]:
z=np.random.random(10)
print(z.argmax()) 
z[z.argmax()]=0
print(z) 

5
[0.63861038 0.6530065  0.543548   0.77731161 0.5113212  0.
 0.23010593 0.54608515 0.68581842 0.38839321]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [136]:
z=np.zeros((5,5), [('x',float),('y',float)])
z['x'],z['y']=np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(z) 

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [138]:
x=np.arange(8)
y=x+0.5 
c=1.0/np.subtract.outer(x,y) 
print(np.linalg.det(c))  

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [139]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps) 

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [141]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z) 

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [142]:
z=np.arange(100) 
v=np.random.uniform(0,100) 
index =(np.abs(z-v)).argmin()
print(z[index]) 

53


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

Save and commit your work

In [16]:
import jovian

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

Save and commit your work.

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

Save and commit your work

In [20]:
import jovian

In [21]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/aakashns/numpy-100-exercises


'https://jovian.ml/aakashns/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

Save and commit your work

In [22]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


Congratulations on completing the 100 exercises, well done! 