In [1]:
import numpy as np 

Write a Numpy program to get the Numpy version and show the Numpy build configuration 

In [2]:
np.__version__

'1.26.0'

2. Write a NumPy program to get help with the add function. 

In [3]:
print(np.info(np.add)) 

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Write a NumPy program to test whether none of the elements of a given array are zero. 

In [2]:
x=[5,7,3,0,6]
print(np.all(x)) 

False


4. Write a NumPy program to test if any of the elements of a given array are non-zero.  

In [7]:
x=[5,7,3,0,6]
print(np.any(x))  

True


8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not 

In [8]:
import numpy as np
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar([3.1])) 

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number:
[ True False False False False  True]
Checking for real number:
[False  True  True  True  True False]
Checking for scalar type:
True
False


13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 

In [10]:
print(np.zeros(10)),
print(np.ones(10)),
print(np.ones(10)*5) 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


Write a NumPy program to create an array of integers from 30 to 70. 

In [11]:
arr=np.arange(30,70) 
arr 

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69])

Write a NumPy program to create a 3x3 identity matrix. 

In [12]:
mat=np.identity(3) 
mat 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

17. Write a NumPy program to generate a random number between 0 and 1 

In [22]:
x=np.random.rand()  
x  

0.5750222747930186