We can now compute the dot product of the two vectors using the np.dot function.

In [1]:
import numpy as np

%%time - for see the execution time

In [3]:
import numpy as np

In [4]:
a=np.array([[1,2],[3,4]])

In [5]:
b=np.array([[5,6]])

In [7]:
a.shape

(2, 2)

In [8]:
b.shape

(1, 2)

In [11]:
c=np.concatenate((a,b))

In [12]:
c 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [13]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6,9,10],
            [7,8,11,16]])

In [14]:
c=np.concatenate((a,b),axis=1)
c 

array([[ 1,  2,  5,  6,  9, 10],
       [ 3,  4,  7,  8, 11, 16]])

In [15]:
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])

In [16]:
arr3 = np.array([[11, 12, 13, 14], 
                 [15, 16, 17, 18], 
                 [19, 11, 12, 13]])

In [17]:
arr2*arr3 

array([[ 11,  24,  39,  56],
       [ 75,  96, 119, 144],
       [171,  11,  24,  39]])

In [18]:
arr2+3 

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12,  4,  5,  6]])

In [20]:
arr2%5

array([[1, 2, 3, 4],
       [0, 1, 2, 3],
       [4, 1, 2, 3]], dtype=int32)

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 1, 2, 3]])

In [22]:
np.linspace(3,27,12)

array([ 3.        ,  5.18181818,  7.36363636,  9.54545455, 11.72727273,
       13.90909091, 16.09090909, 18.27272727, 20.45454545, 22.63636364,
       24.81818182, 27.        ])

In [24]:
np.linspace(3,27,12).reshape(4,3)

array([[ 3.        ,  5.18181818,  7.36363636],
       [ 9.54545455, 11.72727273, 13.90909091],
       [16.09090909, 18.27272727, 20.45454545],
       [22.63636364, 24.81818182, 27.        ]])